<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DG" ignored="0" name="BankingApp Test(failed)" tests="5" failures="5" timestamp="2022-02-27T20:22:39 IST" time="90.833" errors="0">
  <testcase name="loginDDT" time="2.707" classname="com.iNetBanking.testCases.TC_LoginTest_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.iNetBanking.testCases.TC_LoginTest_002.loginDDT(TC_LoginTest_002.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="2.538" classname="com.iNetBanking.testCases.TC_LoginTest_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.iNetBanking.testCases.TC_LoginTest_002.loginDDT(TC_LoginTest_002.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="3.23" classname="com.iNetBanking.testCases.TC_LoginTest_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.iNetBanking.testCases.TC_LoginTest_002.loginDDT(TC_LoginTest_002.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginTest" time="4.084" classname="com.iNetBanking.testCases.TC_LoginTest_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.iNetBanking.testCases.TC_LoginTest_001.loginTest(TC_LoginTest_001.java:23)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="addNewCustomer" time="36.237" classname="com.iNetBanking.testCases.TC_AddCustomerTest_003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.iNetBanking.testCases.TC_AddCustomerTest_003.addNewCustomer(TC_AddCustomerTest_003.java:40)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addNewCustomer -->
</testsuite> <!-- BankingApp Test(failed) -->
